version: "3"
services:
    postgres:
        image: postgres:10-alpine
        container_name: mx-proposal-postgres
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=mx-backend-proposal
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
    server:
        image: murilodev/mx-backend-proposal:latest
        ports:
            - "8080:8080"